### ISSUE TITLE
Add OpenStreetMap support

### ISSUE THREAD

**Issue by m-rey** [thepublictransport/thepublictransport-app#21]
It would be nice to be able to use OpenStreetMap as a map instead of Google Maps (or at least to have the option of using OpenStreetMap). 

OpenStreetMap offers a collaborative platform to add and update map data, including public transport stops etc. 
Errors in the data can be fixed much faster in OpenStreetMap than in Google. Also, OpenStreetMap is an open community project, while Google maps isn't. In the sprit of open source, as this application is, using OpenStreetMap would be nice. 

If the possibility of using Google maps should still be available, an option in the settings to switch between maps would be ideal.

**Comment by PDesire** [comment]
OpenStreetMap will be the future of our app. But: We are right now focused to create our own public transport standard called PTB. I would add this into the rebuild of the TPT app to the PTB standard then. 

About that: We could either embed it as png with flutter_map, or writing our own module with skia bindings etc. which would require much more work. What would you suggest ? @m-rey
