### ISSUE TITLE
Tier/Lime/Circ Integration

### ISSUE THREAD

**Issue by spnda** [thepublictransport/thepublictransport-app#7]
Da Google Maps jetzt mit dem neusten Update auch Funktionen für Lime integriert hat, fände ich es auch eine gute Idee, dies hier ein zu bauen. 
Elektro Scooter wie Lime sind auch Öffentliche Verkehrsmittel geworden heutzutage und sollten definitiv in dieser App einen Platz finden-

![image](https://media.discordapp.net/attachments/442748131898032138/619926129326686229/unknown.jpg?width=637&height=910)

(Wenn ich Zeit habe und ich die Lime API finde, wäre es für mich kein Problem dies selbst zu programmieren und mit einem PR anzufragen.)

EN (@PDesire):
Google Maps has now support for Lime. It would be a good idea to integrate it into our app.
Some API docs with the Lime API are here: https://github.com/ubahnverleih/WoBike/blob/master/Lime.md
It requires some OAuth with your phone number so we need some views for phone number registration & validation too.

**Comment by PDesire** [comment]
Brilliante Idee, würde ich auch so unterstützen, vielen Dank ! 

Vielleicht hilft ja auch die Info dir: https://github.com/ubahnverleih/WoBike/blob/master/Lime.md
So wie ich das lese will Lime eine Auth via Tel. Nummer, ist aber bei den anderen Anbietern nicht anders.

Bei Fragen zum Code stehe ich gerne zur Verfügung. Und ich freue mich schon auf das PR review :D 

Setze jetzt die Flags feature und in progress, bei Änderungen bitte Bescheid geben.

**Comment by spnda** [comment]
Das einzige Problem was mir bis jetzt auffällt ist, dass es wahrscheinlich sehr kompliziert wäre verschiedene Accounts für verschiedene Anbieter in einer App zu speichern und zu benutzen.
Ich würde sagen, man sollte zuerst nur Lime integrieren und dann später über Tier, Circ etc. nachdenken.

**Comment by PDesire** [comment]
Klingt gut, vielleicht setzen wir uns auch in der Zukunft mit den anderen Anbietern in Verbindung, vielleicht sind sie ja interessiert ;)

**Comment by PDesire** [comment]
Bald kommt neuer release mit diesen features. Issue Closed
