### ISSUE TITLE
Hacktoberfest: We need your help !

### ISSUE THREAD

**Issue by PDesire** [thepublictransport/thepublictransport-app#8]
Well this app is pretty new, and still has some bugs we need to fix. So the 'The Public Transport' team wants to ask you for your help ! 

Bugfixes: 
So if you have any improvement or bugfix, please help us fixing them.

Thankyou and have a nice Hacktoberfest !!!!

**Comment by hkp27299** [comment]
Means you want to change your app into English or what? i am flutter developer so i can try to fix bugs but i am not translator you want to fix any specific bugs? help me to what you exactly what from us?

**Comment by Rian0702** [comment]
Would love to help. Any known issues or bugs?

**Comment by lauvrenn** [comment]
Me as well, I'd be happy to help 🙆

**Comment by aitorres** [comment]
You can count me in, too!

**Comment by madhukesh048** [comment]
I Can help you as well!

**Comment by PDesire** [comment]
Well we finally released the first stable release of TPT yesterday ! But ofc some bugs are inside. For example sometimes we get an 'cannot get iterator' bug on some flare animations. That mostly depends on the location you are. Could you guys tell me some other bugs you maybe found ? :D

**Comment by madhukesh048** [comment]
@PDesire sure!

**Comment by PDesire** [comment]
@madhukesh048 Did you try to do a debug or release build ? Is that a serious issue which maybe requires a separate issue ? ;)

**Comment by PDesire** [comment]
So @lauvrenn @Rian0702 @aitorres @madhukesh048 after some while I created now several issues and features we need to take care about:

- https://github.com/thepublictransport/thepublictransport-app/issues/11
- https://github.com/thepublictransport/thepublictransport-app/issues/10
- https://github.com/thepublictransport/thepublictransport-app/issues/9
- https://github.com/thepublictransport/thepublictransport-app/issues/7 (English translation included)
- https://github.com/thepublictransport/flixbus-server/issues/1

**Comment by madhukesh048** [comment]
hey @PDesire i cloned your project and tried debugging it on my device but im not able to build

**Comment by PDesire** [comment]
@madhukesh048 What errors do you get ?

**Comment by steppefox** [comment]
@PDesire hey, looks like it's not possible to build the app in dev without API keys. Could you share staging/testing API keys in DM by email or Telegram?

**Comment by diegoramosb** [comment]
Hey @PDesire can I get the API keys too please? I'd like to contribute but I can´t build the app either. Thanks!

**Comment by PDesire** [comment]
@diegoramosb Where should i send it to ? E-Mail ? Telegram ?

**Comment by PDesire** [comment]
Translation Engine is done, but ofc some people can help with translation. 

Here's how it looks like in english: https://github.com/thepublictransport/thepublictransport-app/blob/master/locale/i18n_en.json

**Comment by diegoramosb** [comment]
@PDesire Could you e-mail it to me please?

**Comment by EddyHu71** [comment]
Sorry for late reply. Recently, I really busy.
