### ISSUE TITLE
i18n: Extract existing string values & pack to class // Hacktoberfest 2019

### ISSUE THREAD

**Issue by PDesire** [thepublictransport/thepublictransport-app#9]
As every string in TPT is hardcoded, it would be nice to extract every string included in the app and pack it into a Dart class with static values.

like: `static String <String ID> = "String"`

Probably something for german speakers.

**Comment by luko0610** [comment]
Hello!
I could help with that. Is it still available?

**Comment by PDesire** [comment]
@luko0610 It is, thankyou !

**Comment by PDesire** [comment]
Done !
